### ISSUE TITLE
Usage with redux-thunk?

### ISSUE THREAD

**Issue by seansfkelley** [wyze/redux-debounce#2]
I have a thunk action I would like to debounce, but the requirement for FSA compliance means that this isn't possible, because the function is clearly not an FSA. I was intending to [attach the `meta` directly to the function itself](https://github.com/ryanseddon/redux-debounced/issues/4#issuecomment-193964139): 

```
function action() {
  const thunk = (dispatch, getState) => {
    loadStuffFromServerPromise()
    .then(stuff => dispatch({
      type: 'type',
      payload: stuff
    }));
  };
  thunk.meta = {
    debounce: 'my-thunk-action'
  };
  return thunk;
}
```

Which should work in theory, except that is fails the FSA check. Can the check be relaxed to just check for the necessary `meta.debounce`? Alternatively, is there some other pattern here that uses plain objects I'm missing? This action is implemented with a promise for a server call, as in the simplified example above, so I think I'm stuck with thunk actions.

**Comment by wyze** [comment]
It is not meant to work that way since thunk just calls the function and wouldn't look at a `meta` prop on the function itself. Are you using any kind of promise middleware by chance?

**Comment by seansfkelley** [comment]
I tried something analogous using [redux-debounced](https://github.com/ryanseddon/redux-debounced) by putting the debouncing ahead of the thunk middleware, and it works as expected. At first it seems a little weird, I agree, but giving it some more thought I think it's not that unreasonable: whether or not you dispatch FSA-compliant actions is, I assert, not really a concern for this library, only whether or not your actions (whatever they may be) have a `meta.debounce` and consequently should be handled before being passed down to chain to whatever else middleware. 

I've played with promise middlewares, and I don't think they solve this problem: I want to debounce the server call that creates the promise, and a promise middleware only operates once the promise has been created. I could debounce the promise-creating function, which is what I used to do until it caused bugs: multiple stores would share the same debounced instance of the function, which would prevent all except one of the stores from being able to make a request at any given time. The appeal of this library or redux-debounced is the consistent interface and non-singleton-ness of the behavior.

There are other large-scale patterns I can adopt, like redux-saga, that might end up working around this problem, but that's a lot to change for a relatively simple desired behavior.

In any case, it's possible that I just have a rare use-case (though not unheard of, given https://github.com/ryanseddon/redux-debounced/issues/4) that requires behavior you don't want to support, in which case I'm happy to close this out and just maintain a fork for my uses.

**Comment by wyze** [comment]
I'd be willing to support non-FSA actions. Do you think it would be best as a per-action basis or like a global setting when defining the middleware?

I whipped up this to show you what I came up with: http://esnextb.in/?gist=b502436196935571205d
It is on a per-action basis in this example. Relevant lines are 24 and 56.

**Comment by seansfkelley** [comment]
I don't mean to derail your project with this one feature request, but I think the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) applies here: whether or not your inputs are FSAs ought not to be a concern of this middleware, only that they are a thing that is debounce-able, that is, has a `meta.debounce`. For sure, you should accept FSAs, but probably also things that duck-type properly for your purposes (such as these thunks). In other words, `isFSA` is kind of roundabout. If I'm going to assert FSA-ness, I will probably use something like [redux-validate-fsa](https://github.com/buunguyen/redux-validate-fsa) to make sure that my actions are FSAs at the end of the middleware stack, and not necessarily anywhere in between.

**Comment by wyze** [comment]
I am going to close this and keep the library as is. There are a couple handfuls of other redux libraries that force FSA. I will make that message more prominent. Thank you for raising your concerns.
